/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8bc2f35798b30d393a2fbdb9374737c2)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
